package models

import (
	"time"

	"github.com/sikehish/Go-Event-Booking-API/db"
)

type Event struct {
	ID          int64
	Name        string    `binding:"required"`
	Description string    `binding:"required"`
	Location    string    `binding:"required"`
	DateTime    time.Time `binding:"required"`
	UserID      int64
}

// var events = []Event{}

func (e *Event) Save() error {
	// events = append(events, e)
	query := `
	INSERT INTO events (name, description, location, date_time, user_id) VALUES (?, ?, ?, ?,?)`
	stmt, err := db.DB.Prepare(query) //Prepare creates a prepared statement for later queries or executions. Multiple queries or executions may be run concurrently from the returned statement.
	if err != nil {
		return err
	}

	defer stmt.Close() //eleases any resources associated with the prepared statement.

	result, err := stmt.Exec(e.Name, e.Description, e.Location, e.DateTime, e.UserID) //The order in which values have been mentioned in the query string has to be followed

	if err != nil {
		return err
	}

	id, err := result.LastInsertId() //LastInsertId returns the integer generated by the database in response to a command. Typically this will be from an "auto increment" column when inserting a new row.
	// fmt.Printf("%v %v", e.ID, id)
	e.ID = id
	return err
}

func GetAllEvents() ([]Event, error) {
	// return events
	query := "SELECT * FROM events"
	rows, err := db.DB.Query(query)
	if err != nil {
		return nil, err
	}

	defer rows.Close() // If Next is called and returns false and there are no further result sets, the Rows are closed automatically and it will suffice to check the result of Err.

	var events []Event

	for rows.Next() {
		var event Event
		err := rows.Scan(&event.ID, &event.Name, &event.Description, &event.Location, &event.DateTime, &event.UserID) //the order has to be the same as the order in which the columns were defined

		if err != nil {
			return nil, err
		}
		events = append(events, event)
	}
	return events, nil

}

func GetEventByID(id int64) (*Event, error) { //We return pointer to Event instead of Event because we want to return nil instead of empty Event struct(easier to check if the struct is empty)
	query := "SELECT * FROM events WHERE id = ?"
	row := db.DB.QueryRow(query, id)

	var event Event
	err := row.Scan(&event.ID, &event.Name, &event.Description, &event.Location, &event.DateTime, &event.UserID)

	if err != nil {
		return nil, err
	}

	return &event, nil
}

func (event Event) Update() error {
	query := `
	UPDATE events
	SET name=?, description=?,location=?, date_time=?
	WHERE id=? 
	`

	stmt, err := db.DB.Prepare(query)

	if err != nil {
		return err
	}

	defer stmt.Close()

	_, err = stmt.Exec(event.Name, event.Description, event.Location, event.DateTime, event.ID)

	return err
}

func (event Event) Delete() error {
	query := `DELETE FROM events WHERE id=?`
	stmt, err := db.DB.Prepare(query)

	if err != nil {
		return err
	}

	defer stmt.Close()

	_, err = stmt.Exec(event.ID)

	return err
}
